# Generated by Django 3.2.6 on 2021-10-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_jewelry_jewelry_type'),
        ('customers', '0002_auto_20211022_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='jewelry',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='jewelry',
            field=models.ManyToManyField(to='Product.Jewelry'),
        ),
    ]
