# Generated by Django 3.2.6 on 2021-10-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20211022_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='order',
        ),
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.ManyToManyField(to='customers.Order'),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(to='customers.WishList'),
        ),
    ]
