# Generated by Django 3.2.6 on 2021-10-22 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jewelry_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('picture', models.ImageField(unique=True, upload_to='')),
                ('description', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('stock_count', models.IntegerField()),
                ('slug', models.SlugField(default=None)),
                ('price', models.BigIntegerField()),
                ('star', models.SmallIntegerField()),
                ('jewelry_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Product.jewelry_type')),
            ],
        ),
    ]
