# Generated by Django 3.2.6 on 2021-10-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='image',
            field=models.ImageField(default='/No product image.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='jewelry_type',
            name='picture',
            field=models.ImageField(default='/No product image.png', unique=True, upload_to=''),
        ),
    ]
