# Generated by Django 3.2.6 on 2021-10-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20211022_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry_type',
            name='picture',
            field=models.ImageField(default='/No product image.png', upload_to=''),
        ),
    ]
