# Generated by Django 3.2.6 on 2021-10-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_jewelry_jewelry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='star',
            field=models.SmallIntegerField(),
        ),
    ]
