# Generated by Django 3.2.6 on 2021-10-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_jewelry_type_jewels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewelry_type',
            name='jewels',
        ),
    ]
